const TILE=256,cities={北京:[116.3974,39.9093],上海:[121.4737,31.2304],深圳:[114.0579,22.5431],杭州:[120.1551,30.2741],成都:[104.0665,30.5723],广州:[113.2644,23.1291]};
let center={lon:116.3974,lat:39.9093},zoom=12,selected={x:3372,y:1551,z:12,lon:116.3974,lat:39.9093},contrast=false,drag=null,moved=false;
const $=s=>document.querySelector(s),stage=$('#stage'),map=$('#map');
function toWorld(lon,lat,z){const s=TILE*2**z,n=Math.sin(lat*Math.PI/180);return{x:(lon+180)/360*s,y:(.5-Math.log((1+n)/(1-n))/(4*Math.PI))*s}}
function toLonLat(x,y,z){const s=TILE*2**z,n=Math.PI-2*Math.PI*y/s;return{lon:x/s*360-180,lat:180/Math.PI*Math.atan(Math.sinh(n))}}
function qKey(x,y,z){let q='';for(let i=z;i>0;i--){let d=0,m=1<<(i-1);if(x&m)d++;if(y&m)d+=2;q+=d}return q}
function flash(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(flash.timer);flash.timer=setTimeout(()=>t.classList.remove('show'),2200)}
function copy(v){navigator.clipboard.writeText(v);flash('已复制到剪贴板')}
function render(){const r=map.getBoundingClientRect(),w=Math.max(r.width,700)+512,h=Math.max(r.height,430)+512,c=toWorld(center.lon,center.lat,zoom),minX=c.x-w/2,minY=c.y-h/2,n=2**zoom;stage.style.width=w+'px';stage.style.height=h+'px';stage.innerHTML='';
 for(let y=Math.floor(minY/TILE);y<=Math.floor((minY+h)/TILE);y++)for(let x=Math.floor(minX/TILE);x<=Math.floor((minX+w)/TILE);x++){if(y<0||y>=n)continue;const tx=(x%n+n)%n,cell=document.createElement('div');cell.className='tile-cell'+(selected.x===tx&&selected.y===y&&selected.z===zoom?' selected':'');cell.style.left=x*TILE-minX+'px';cell.style.top=y*TILE-minY+'px';cell.innerHTML=`<img src="https://tile.openstreetmap.org/${zoom}/${tx}/${y}.png" alt="" draggable="false"><div class="tile-grid"><span><b>${zoom}</b><i>/</i>${tx}<i>/</i>${y}</span></div>`;stage.appendChild(cell)}
 stage.classList.toggle('contrast',contrast);updateInfo();
}
function updateInfo(){const nw=toLonLat(selected.x*TILE,selected.y*TILE,selected.z),se=toLonLat((selected.x+1)*TILE,(selected.y+1)*TILE,selected.z),q=qKey(selected.x,selected.y,selected.z);$('#z-val').textContent=selected.z;$('#x-val').textContent=selected.x;$('#y-val').textContent=selected.y;$('#lon-val').textContent=selected.lon.toFixed(6)+'°';$('#lat-val').textContent=selected.lat.toFixed(6)+'°';$('#quad-val').textContent=q;$('#nw-val').textContent=`${nw.lon.toFixed(5)}, ${nw.lat.toFixed(5)}`;$('#se-val').textContent=`${se.lon.toFixed(5)}, ${se.lat.toFixed(5)}`;$('#zoom-label').textContent='Z '+zoom;$('#zoom-range').value=zoom;$('#map-status').innerHTML=`<span class="pulse"></span> 网格已开启 <i></i> Z ${zoom} <i></i> ${center.lon.toFixed(4)}°, ${center.lat.toFixed(4)}°`}
function setZoom(z){zoom=Math.max(2,Math.min(19,z));const p=toWorld(selected.lon,selected.lat,zoom);selected={...selected,x:Math.floor(p.x/TILE),y:Math.floor(p.y/TILE),z:zoom};render()}
function choose(cx,cy){const r=map.getBoundingClientRect(),w=Math.max(r.width,700)+512,h=Math.max(r.height,430)+512,c=toWorld(center.lon,center.lat,zoom),wx=c.x-w/2+(cx-r.left)+(w-r.width)/2,wy=c.y-h/2+(cy-r.top)+(h-r.height)/2,ll=toLonLat(wx,wy,zoom);selected={x:Math.floor(wx/TILE),y:Math.floor(wy/TILE),z:zoom,...ll};render()}
map.addEventListener('wheel',e=>{e.preventDefault();setZoom(zoom+(e.deltaY<0?1:-1))},{passive:false});map.addEventListener('pointerdown',e=>{const w=toWorld(center.lon,center.lat,zoom);drag={x:e.clientX,y:e.clientY,wx:w.x,wy:w.y};moved=false;map.setPointerCapture(e.pointerId)});map.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;moved=moved||Math.hypot(dx,dy)>4;center=toLonLat(drag.wx-dx,drag.wy-dy,zoom);render()});map.addEventListener('pointerup',e=>{if(!moved)choose(e.clientX,e.clientY);drag=null});
$('#zoom-in').onclick=()=>setZoom(zoom+1);$('#zoom-out').onclick=()=>setZoom(zoom-1);$('#reset').onclick=()=>{center={lon:116.3974,lat:39.9093};render()};$('#zoom-range').oninput=e=>setZoom(+e.target.value);
document.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>{contrast=b.dataset.layer==='contrast';document.querySelectorAll('[data-layer]').forEach(x=>x.classList.toggle('active',x===b));render()});
$('#search-form').onsubmit=e=>{e.preventDefault();const v=$('#search').value.trim(),hit=cities[v],c=v.split(/[/,，\s]+/).map(Number);if(hit){center={lon:hit[0],lat:hit[1]};render();return}if(c.length===3&&c.every(Number.isFinite)){const z=c[0]|0,x=c[1]|0,y=c[2]|0,n=2**z;if(z<2||z>19)return flash('缩放级别需在 2-19 之间');if(x<0||x>=n||y<0||y>=n)return flash('Z'+z+' 切片范围 0-'+(n-1));zoom=z;const ll=toLonLat((x+0.5)*TILE,(y+0.5)*TILE,z);center=ll;selected={x,y,z,...ll};render();return flash('已定位到切片 '+z+'/'+x+'/'+y)}if(c.length>=2&&c.every(Number.isFinite)){center={lon:c[0],lat:c[1]};render();return}flash('试试“上海”、经纬度 121.47,31.23 或切片 12/3372/1551')};
$('#locate').onclick=()=>navigator.geolocation?.getCurrentPosition(p=>{center={lon:p.coords.longitude,lat:p.coords.latitude};const w=toWorld(center.lon,center.lat,zoom);selected={x:Math.floor(w.x/TILE),y:Math.floor(w.y/TILE),z:zoom,...center};render()},()=>flash('无法获取位置，请检查浏览器权限'));
$('#copy-xyz').onclick=()=>copy(`${selected.z}/${selected.x}/${selected.y}`);$('#copy-quad').onclick=()=>copy(qKey(selected.x,selected.y,selected.z));$('#copy-url').onclick=()=>copy(`https://tile.openstreetmap.org/${selected.z}/${selected.x}/${selected.y}.png`);window.addEventListener('resize',render);render();
