import { TILE, lonLatToWorld as toWorld, worldToLonLat as toLonLat, quadKey as qKey, parseQuery, tileCenter as tCenter, tileCenterText as tCenterText, tileUrl, ATTRIBUTIONS, MIN_Z, MAX_Z, lonLatToTerrainTile as toTerrainTile, terrainTileBounds as terrainBounds, terrainTilePath as terrainPath, visibleTerrainTiles as visTerrain } from './tile.js';
let center={lon:116.3974,lat:39.9093},zoom=12,selected={x:3372,y:1551,z:12,lon:116.3974,lat:39.9093},layer='standard',gridMode='xyz',drag=null,moved=false;
const $=s=>document.querySelector(s),stage=$('#stage'),map=$('#map');
function flash(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(flash.timer);flash.timer=setTimeout(()=>t.classList.remove('show'),2200)}
function copy(v){navigator.clipboard.writeText(v);flash('已复制到剪贴板')}
function render(){const r=map.getBoundingClientRect(),w=Math.max(r.width,700)+512,h=Math.max(r.height,430)+512,c=toWorld(center.lon,center.lat,zoom),minX=c.x-w/2,minY=c.y-h/2,n=2**zoom,base=layer==='contrast'?'standard':layer;stage.style.width=w+'px';stage.style.height=h+'px';stage.innerHTML='';
 for(let y=Math.floor(minY/TILE);y<=Math.floor((minY+h)/TILE);y++)for(let x=Math.floor(minX/TILE);x<=Math.floor((minX+w)/TILE);x++){if(y<0||y>=n)continue;const tx=(x%n+n)%n,cell=document.createElement('div');cell.className='tile-cell'+(selected.x===tx&&selected.y===y&&selected.z===zoom?' selected':'');cell.style.left=x*TILE-minX+'px';cell.style.top=y*TILE-minY+'px';cell.innerHTML=`<img src="${tileUrl(base,tx,y,zoom)}" alt="" draggable="false"><div class="tile-grid"><span><b>${zoom}</b><i>/</i>${tx}<i>/</i>${y}</span></div>`;stage.appendChild(cell)}
 if(gridMode==='terrain'){const st=toTerrainTile(selected.lon,selected.lat,zoom);for(const c of visTerrain(minX,minY,w,h,zoom)){const g=document.createElement('div');g.className='tgrid-cell'+(selected.z===zoom&&st.x===c.x&&st.y===c.y?' selected':'');g.style.left=c.left+'px';g.style.top=c.top+'px';g.style.width=c.width+'px';g.style.height=c.height+'px';g.innerHTML=`<span><b>${zoom}</b><i>/</i>${c.x}<i>/</i>${c.y}</span>`;stage.appendChild(g)}}
 stage.classList.toggle('contrast',layer==='contrast');stage.classList.toggle('imagery',layer==='imagery');stage.classList.toggle('terrain',layer==='terrain');stage.classList.toggle('scheme-terrain',gridMode==='terrain');updateInfo();
}
function updateInfo(){const nw=toLonLat(selected.x*TILE,selected.y*TILE,selected.z),se=toLonLat((selected.x+1)*TILE,(selected.y+1)*TILE,selected.z),q=qKey(selected.x,selected.y,selected.z),tc=tCenter(selected.x,selected.y,selected.z);$('#z-val').textContent=selected.z;$('#x-val').textContent=selected.x;$('#y-val').textContent=selected.y;$('#lon-val').textContent=selected.lon.toFixed(6)+'°';$('#lat-val').textContent=selected.lat.toFixed(6)+'°';$('#tc-lon').textContent=tc.lon.toFixed(6)+'°';$('#tc-lat').textContent=tc.lat.toFixed(6)+'°';$('#quad-val').textContent=q;$('#nw-val').textContent=`${nw.lon.toFixed(5)}, ${nw.lat.toFixed(5)}`;$('#se-val').textContent=`${se.lon.toFixed(5)}, ${se.lat.toFixed(5)}`;$('#zoom-label').textContent='Z '+zoom;$('#zoom-range').value=zoom;$('#map-status').innerHTML=`<span class="pulse"></span> 网格已开启 <i></i> Z ${zoom} <i></i> ${center.lon.toFixed(4)}°, ${center.lat.toFixed(4)}°`;const tt=toTerrainTile(selected.lon,selected.lat,selected.z),tb=terrainBounds(tt.x,tt.y,selected.z);$('#t-xyz').textContent=`${selected.z} / ${tt.x} / ${tt.y}`;$('#t-grid').textContent=`EPSG:4326 四叉树 · 2^${selected.z+1}×2^${selected.z}`;$('#t-path').textContent=terrainPath(tt.x,tt.y,selected.z);$('#t-sw').textContent=`${tb.south.toFixed(5)}, ${tb.west.toFixed(5)}`;$('#t-ne').textContent=`${tb.north.toFixed(5)}, ${tb.east.toFixed(5)}`;$('#attribution').textContent=ATTRIBUTIONS[layer==='contrast'?'standard':layer]}
function setZoom(z,ax,ay){z=Math.max(MIN_Z,Math.min(MAX_Z,z));if(ax!==undefined){const r=map.getBoundingClientRect(),w=Math.max(r.width,700)+512,h=Math.max(r.height,430)+512,c=toWorld(center.lon,center.lat,zoom),px=ax-r.left+(w-r.width)/2,py=ay-r.top+(h-r.height)/2,ll=toLonLat(c.x-w/2+px,c.y-h/2+py,zoom),w2=toWorld(ll.lon,ll.lat,z);center=toLonLat(w2.x-px+w/2,w2.y-py+h/2,z)}zoom=z;const p=toWorld(selected.lon,selected.lat,zoom);selected={...selected,x:Math.floor(p.x/TILE),y:Math.floor(p.y/TILE),z:zoom};render()}
function choose(cx,cy){const r=map.getBoundingClientRect(),w=Math.max(r.width,700)+512,h=Math.max(r.height,430)+512,c=toWorld(center.lon,center.lat,zoom),wx=c.x-w/2+(cx-r.left)+(w-r.width)/2,wy=c.y-h/2+(cy-r.top)+(h-r.height)/2,ll=toLonLat(wx,wy,zoom);selected={x:Math.floor(wx/TILE),y:Math.floor(wy/TILE),z:zoom,...ll};render()}
map.addEventListener('wheel',e=>{e.preventDefault();setZoom(zoom+(e.deltaY<0?1:-1),e.clientX,e.clientY)},{passive:false});map.addEventListener('pointerdown',e=>{if(e.target.closest('button,input,a'))return;const w=toWorld(center.lon,center.lat,zoom);drag={x:e.clientX,y:e.clientY,wx:w.x,wy:w.y};moved=false;map.setPointerCapture(e.pointerId)});map.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;moved=moved||Math.hypot(dx,dy)>4;center=toLonLat(drag.wx-dx,drag.wy-dy,zoom);render()});map.addEventListener('pointerup',e=>{if(!moved)choose(e.clientX,e.clientY);drag=null});
$('#zoom-in').onclick=()=>setZoom(zoom+1);$('#zoom-out').onclick=()=>setZoom(zoom-1);$('#reset').onclick=()=>{center={lon:116.3974,lat:39.9093};render()};$('#zoom-range').oninput=e=>setZoom(+e.target.value);
document.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>{layer=b.dataset.layer;document.querySelectorAll('[data-layer]').forEach(x=>x.classList.toggle('active',x===b));render()});
document.querySelectorAll('[data-grid]').forEach(b=>b.onclick=()=>{gridMode=b.dataset.grid;document.querySelectorAll('[data-grid]').forEach(x=>x.classList.toggle('active',x===b));render();flash(gridMode==='terrain'?'地形网格：Quantized-Mesh 地理四叉树（TMS，y 自南向北）':'XYZ 网格：Web 墨卡托')});
$('#search-form').onsubmit=e=>{e.preventDefault();const r=parseQuery($('#search').value);if(r.type==='center'){center={lon:r.lon,lat:r.lat};render();return}if(r.type==='tile'){zoom=r.z;center={lon:r.lon,lat:r.lat};selected={x:r.x,y:r.y,z:r.z,lon:r.lon,lat:r.lat};render();return}if(r.type==='terrain'){zoom=r.z;center={lon:r.lon,lat:r.lat};const w=toWorld(center.lon,center.lat,zoom);selected={x:Math.floor(w.x/TILE),y:Math.floor(w.y/TILE),z:zoom,...center};render();flash('已定位到地形切片 '+terrainPath(r.x,r.y,r.z)+'（TMS 地理网格）');return}flash(r.message)};
$('#locate').onclick=()=>navigator.geolocation?.getCurrentPosition(p=>{center={lon:p.coords.longitude,lat:p.coords.latitude};const w=toWorld(center.lon,center.lat,zoom);selected={x:Math.floor(w.x/TILE),y:Math.floor(w.y/TILE),z:zoom,...center};render()},()=>flash('无法获取位置，请检查浏览器权限'));
$('#copy-xyz').onclick=()=>copy(`${selected.z}/${selected.x}/${selected.y}`);$('#copy-quad').onclick=()=>copy(qKey(selected.x,selected.y,selected.z));$('#copy-tile-center').onclick=()=>copy(tCenterText(selected.x,selected.y,selected.z));$('#copy-terrain').onclick=()=>{const tt=toTerrainTile(selected.lon,selected.lat,selected.z);copy(terrainPath(tt.x,tt.y,selected.z))};$('#copy-url').onclick=()=>copy(tileUrl(layer==='contrast'?'standard':layer,selected.x,selected.y,selected.z));window.addEventListener('resize',render);render();
